#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script file name: diff_RBR_SBE.py
Author: Etienne Poirier, IRD, Plouzané
Date created: 2025-06-30
Last update: 2026-01-09
Description: various functions to plot comparison graphs
between RBR and SBE data profiles (marine probes)
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker
import os
import warnings

# warnings format for warnings messages to be visible
warnings.simplefilter("always", UserWarning)

# %%
# formatting the warning messages


def custom_warning_format(message, category, filename, lineno, line=None):
    return f"\n⚠️  WARNING: {message}\n\n"


warnings.formatwarning = custom_warning_format

# %% parse_somlit_file


def parse_somlit_file(filepath):
    """
    Function is a parser to read a CSV Somlit type file generated by Somlit RBR toolbox
    Not used because missing channels in the final somlit file compared with what
    we want to compare in the SBE data (more channels)

    Parameters
    ----------
    filepath : str
        path to the Somlit csv file

    Raises
    ------
    ValueError
        regarding the format of the first line of the somlit csv

    Returns
    -------
    df : dataframe
        data of the somlit csv sorted in a dataframe

    """
    """
    Parses a SOMLIT-like CSV file with header and metadata.

    Args:
        filepath (str): Path to the input file.

    Returns:
        pd.DataFrame: Cleaned data as DataFrame.
    """

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Find the line that starts with 'ID_SITE' – it's the header
    for i, line in enumerate(lines):
        if line.strip().startswith("ID_SITE"):
            header_idx = i
            break
    else:
        raise ValueError("No header line starting with 'ID_SITE' found.")

    # Now use pandas to read from that line onward
    df = pd.read_csv(
        filepath,
        sep=";",
        skiprows=header_idx,  # skip line with variable too
        encoding="utf-8"
    )

    # Drop completely empty rows (e.g. lines of just semicolons)
    df.dropna(how="all", inplace=True)

    # Remove first row having the units
    df = df.iloc[1:].reset_index(drop=True)

    # Combine date + time into datetime
    df["DATETIME"] = pd.to_datetime(df["DATE"] + " " + df["HEURE"])
    # Convert to datetime64 format
    df['DATETIME'] = pd.to_datetime(df['DATETIME'])

    # Optional: reorder or drop columns
    df = df[["DATETIME", "ID_SITE", "TEMPERATURE",
             "FLUORESCENCE", "PAR", "SALINITE", "PROFONDEUR"]]

    # assign DATETIME colmun as index
    df.set_index('DATETIME', inplace=True)

    return df


# %% read_RBR_csv

def read_RBR_csv(file_path):
    '''
    Function, parser to read a csv file generated by procRSK function and store
    it in a dataframe

    Parameters
    ----------
    file_path : str
        path to the processed csv with RBR data either down or upcast

    Returns
    -------
    df : dataframe
        Dataframe withe the data properly stored to be used later  
    '''

    with open(file_path, "r") as f:
        lines = f.readlines()

    # Step 2: Find the last line starting with '//'
    header_line_idx = None
    for idx, line in enumerate(lines):
        if line.startswith("//"):
            header_line_idx = idx

    # Step 3: Read the file into DataFrame, skipping earlier lines
    # Beware of sep ',   ' 4 spaces after comma
    df = pd.read_csv(
        file_path,
        sep=',    ',
        skiprows=header_line_idx + 1,     # Skip all lines before actual data
        header=None,                      # No header in data part
        engine="python"
    )

    # Step 4: Set the header from the last '//' line
    column_names = lines[header_line_idx].lstrip("//").strip().split(",    ")
    df.columns = column_names

    # remove line with nan
    df = df.dropna()

    # Convert the first column to datetime using your format
    df.iloc[:, 0] = pd.to_datetime(
        df.iloc[:, 0], format='%Y-%m-%dT%H:%M:%S.%f')

    # Set the first column as the index, and avoid warning caused
    # by aving diffrent object types in the index: str, numerical, etc...
    df[df.columns[0]] = df[df.columns[0]].infer_objects()
    df.set_index(df.columns[0], inplace=True)

    return df

# %% parse_custom_sbe


def parse_custom_sbe(filepath):
    '''
    Function, parser specially adapted for sbe file for sept 2025
    sbe file generation is done by Emily manually and column names, order varies
    which programd don't like. parser must be adapted or adaptative

    Parameters
    ----------
    filepath : str
        Path to the sbe csv file to read

    Returns
    -------
    df : dataframe
        dataframe to be used in later processing with all seb data inside

    '''
    # Read file, skip second line (units), first line is header
    df = pd.read_csv(
        filepath,
        sep=';',
        skiprows=[1],  # skip the units row
        decimal=',',    # interpret comma as decimal separator
        dayfirst=True,  # because date format is DD/MM/YYYY
    )

    # Combine date and time into a datetime column
    df['DATETIME'] = pd.to_datetime(
        df['DD MMM YYYY'] + ' ' + df['HH:MM:SS'], dayfirst=True)

    # Set DATETIME as index
    df.set_index('DATETIME', inplace=True)

    # Optional: drop original date/time columns if you want
    df.drop(columns=['DD MMM YYYY', 'HH:MM:SS'], inplace=True)

    return df

# %% rename_sbe_columns


def rename_sbe_columns(df_sbe, df_rbr):
    '''
    Function to rename the columns of sbe df with the ones from rbr df using 
    position id
    + apply a factor to convert DO from ml/L (sbe) to micromol/L (RBR)

    Parameters
    ----------
    df_sbe : dataframe
       sbe dataframe comes from parser function above
    df_rbr : dataframe
        rbr dataframe comes from the parser function above


    Returns
    -------
    df_sbe : dataframe
       columns have been renamed to be the same as rbr and ease the comparison

    '''
    # expected SBE columns (before renaming), list the excpected column names in SBE csv file
    expected_columns = {
        'temp',
        'FLUO',
        'Par',
        'conductivité',
        'Oxygène',
        'turbidité',
        'Sal00',
        'profondeur',
        'densité',
    }
    # find unexpected columns
    unexpected_cols = set(df_sbe.columns) - expected_columns
    if unexpected_cols:
        warnings.warn(
            f"Unexpected column(s) found in SBE dataframe: {
                sorted(unexpected_cols)}"
        )
    # unit convsersion for DO
    # apply a factor to DO values from SBE to convert units
    # from ml/L to micromol/L
    df_sbe['Oxygène'] = df_sbe['Oxygène'] * 44.66

    # rename columns as per the RBR names
    rename_dict = {
        'temp': df_rbr.columns[1],
        'FLUO': df_rbr.columns[6],
        'Par': df_rbr.columns[4],
        'conductivité': df_rbr.columns[0],
        'Oxygène': df_rbr.columns[3],
        'turbidité': df_rbr.columns[8],
        'Sal00': df_rbr.columns[10],
        'profondeur': df_rbr.columns[9],
        'densité': df_rbr.columns[11],
    }

    df_sbe = df_sbe.rename(columns=rename_dict)

    # dodgy option, we had a miror colum with DO values but named differently to
    # allow a comparison with DO_compensated values from RBR
    df_sbe['dissolved_o2_compensated(µmol/L)'] = df_sbe['dissolved_o2_concentration(µmol/L)']

    return df_sbe

# %% plot_and_save_comparisons_all_columns


def plot_and_save_comparisons_all_columns(df_sbe, df_rbr, depth_col='depth(m)', save_folder='figures'):
    """
    Works for upcast and downcast, surpassed by the next function that plots
    everything on the same graph
    Compare all common numeric columns from SBE and RBR:
    - Plot each parameter vs depth on a fig.
    - Plot the difference (SBE - RBR) vs depth (only at common depths) on a fig.
    - Save plots as PNG files

    Args:
        df_sbe (pd.DataFrame): SBE dataset
        df_rbr (pd.DataFrame): RBR dataset
        depth_col (str): Name of the depth column
        save_folder (str): Output directory
    """
    os.makedirs(save_folder, exist_ok=True)

    # Ensure depth columns are numeric and rounded to avoid tiny float mismatches
    df_sbe[depth_col] = pd.to_numeric(
        df_sbe[depth_col], errors='coerce').round(4)
    df_rbr[depth_col] = pd.to_numeric(
        df_rbr[depth_col], errors='coerce').round(4)

    # Find common depths
    common_depths = np.intersect1d(
        df_sbe[depth_col].dropna().unique(), df_rbr[depth_col].dropna().unique())

    if len(common_depths) == 0:
        print("❌ No common depth values found between datasets.")
        return

    # Filter both DataFrames to common depths
    df_sbe_common = df_sbe[df_sbe[depth_col].isin(common_depths)].copy()
    df_rbr_common = df_rbr[df_rbr[depth_col].isin(common_depths)].copy()

    # Sort by depth for plotting
    df_sbe_common = df_sbe_common.sort_values(depth_col)
    df_rbr_common = df_rbr_common.sort_values(depth_col)

    # Get common numeric columns (excluding depth)
    common_cols = [
        col for col in df_rbr.columns
        if col in df_sbe.columns
        and col != depth_col
        and np.issubdtype(df_rbr[col].dtype, np.number)
    ]

    if not common_cols:
        print("❌ No common numeric columns to compare.")
        return

    for param in common_cols:
        print(f"📈 Processing '{param}'...")

        # Merge on depth to align values exactly
        merged = pd.merge(
            df_sbe_common[[depth_col, param]],
            df_rbr_common[[depth_col, param]],
            on=depth_col,
            suffixes=('_sbe', '_rbr')
        )

        if merged.empty:
            print(f"⚠️ No matching depth values with data for '{
                  param}'. Skipping.")
            continue

        # Plot parameter vs depth
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.plot(merged[f"{param}_sbe"], merged[depth_col],
                label='SBE', marker='o')
        ax.plot(merged[f"{param}_rbr"], merged[depth_col],
                label='RBR', marker='x')
        ax.invert_yaxis()
        ax.set_xlabel(f"{param} (units)")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Profile: SBE vs RBR")
        ax.legend()
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        safe_param = ''.join(c if c.isalnum() or c in [
                             '_', '-'] else '_' for c in param)
        fig_path_raw = os.path.join(save_folder, f"{safe_param}_profile.png")
        fig.savefig(fig_path_raw, dpi=150)
        plt.close(fig)

        # Compute difference on common depths
        diff = merged[f"{param}_rbr"] - merged[f"{param}_sbe"]

        # Plot difference
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.plot(diff, merged[depth_col],
                label='RBR - SBE', color='red', marker='.')
        ax.invert_yaxis()
        ax.set_xlabel(f"{param} Difference")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Difference (RBR - SBE)")
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        fig_path_diff = os.path.join(
            save_folder, f"{safe_param}_difference.png")
        fig.savefig(fig_path_diff, dpi=150)
        plt.close(fig)

        print(f"✅ Saved: {fig_path_raw} and {fig_path_diff}")

# %% plot_comparison_up_down
# produces figures with up and down cast and both sbe and rbr data on the same graph, great


def plot_comparisons_up_down(
        df_sbe_down, df_rbr_down,
        df_sbe_up, df_rbr_up,
        depth_col='depth(m)',
        save_folder='figures'):
    '''
    Function to produce figures with up and down cast both on the same graph 
    for both SBE (seabird) and RBR data

    Parameters
    ----------
    df_sbe_down : dataframe
        sbe data downcast
    df_rbr_down : dataframe
        rbr data downcast
    df_sbe_up : dataframe
        sbe data upcast
    df_rbr_up : dataframe
        rbr data upcast
    depth_col : str
        column name with the depth data. The default is 'depth(m)'.
    save_folder : str, optional
        output folder with the figures. The default is 'figures'.

    Returns
    -------
    None

    '''
    os.makedirs(save_folder, exist_ok=True)

    def preprocess(df):
        df = df.copy()
        df[depth_col] = pd.to_numeric(df[depth_col], errors='coerce').round(4)
        return df.dropna(subset=[depth_col])

    df_sbe_down = preprocess(df_sbe_down)
    df_rbr_down = preprocess(df_rbr_down)
    df_sbe_up = preprocess(df_sbe_up)
    df_rbr_up = preprocess(df_rbr_up)

    # Get common numeric columns
    common_cols = [
        col for col in df_rbr_down.columns
        if col in df_sbe_down.columns
        and col != depth_col
        and np.issubdtype(df_rbr_down[col].dtype, np.number)
    ]

    if not common_cols:
        print("❌ No common numeric columns to compare.")
        return

    for param in common_cols:
        print(f"📈 Processing '{param}'...")

        # Prepare merged data for both casts
        def merge_on_depth(df1, df2):
            common_depths = np.intersect1d(
                df1[depth_col].unique(), df2[depth_col].unique())
            df1_common = df1[df1[depth_col].isin(common_depths)]
            df2_common = df2[df2[depth_col].isin(common_depths)]
            return pd.merge(
                df1_common[[depth_col, param]],
                df2_common[[depth_col, param]],
                on=depth_col,
                suffixes=('_sbe', '_rbr')
            ).sort_values(depth_col)

        merged_down = merge_on_depth(df_sbe_down, df_rbr_down)
        merged_up = merge_on_depth(df_sbe_up, df_rbr_up)

        # Profile Plot
        fig, ax = plt.subplots(figsize=(8, 6))
        if not merged_down.empty:
            ax.plot(merged_down[f"{param}_sbe"],
                    merged_down[depth_col], 'o-', label='SBE Downcast')
            ax.plot(merged_down[f"{param}_rbr"],
                    merged_down[depth_col], 'x-', label='RBR Downcast')
        if not merged_up.empty:
            ax.plot(merged_up[f"{param}_sbe"], merged_up[depth_col],
                    'o--', label='SBE Upcast', alpha=0.6)
            ax.plot(merged_up[f"{param}_rbr"], merged_up[depth_col],
                    'x--', label='RBR Upcast', alpha=0.6)

        ax.invert_yaxis()
        ax.set_xlabel(f"{param} (units)")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Profile: Upcast & Downcast (SBE vs RBR)")
        ax.legend()
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        safe_param = ''.join(c if c.isalnum() or c in [
                             '_', '-'] else '_' for c in param)
        fig_path_profile = os.path.join(
            save_folder, f"{safe_param}_profile.png")
        fig.savefig(fig_path_profile, dpi=150)
        plt.close(fig)

        # Difference Plot (RBR - SBE)
        fig, ax = plt.subplots(figsize=(6, 6))
        if not merged_down.empty:
            diff_down = merged_down[f"{param}_rbr"] - \
                merged_down[f"{param}_sbe"]
            ax.plot(diff_down, merged_down[depth_col], 'r-',
                    label='Downcast (RBR - SBE)', marker='.')
        if not merged_up.empty:
            diff_up = merged_up[f"{param}_rbr"] - merged_up[f"{param}_sbe"]
            ax.plot(diff_up, merged_up[depth_col], 'b--',
                    label='Upcast (RBR - SBE)', marker='.')

        ax.invert_yaxis()
        ax.set_xlabel(f"{param} Difference")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Difference (RBR - SBE)")
        ax.grid(True)
        ax.legend()
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        fig_path_diff = os.path.join(
            save_folder, f"{safe_param}_difference.png")
        fig.savefig(fig_path_diff, dpi=150)
        plt.close(fig)

        print(f"✅ Saved: {fig_path_profile} and {fig_path_diff}")
