#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script file name: diff_RBR_SBE.py
Author: Etienne Poirier, IRD, Plouzané
Modified: Aurélien DOMEAU, CNRS, Sète

Date created: 2025-06-30
Last update: 2026-07-16
Description: various functions to plot comparison graphs
between RBR and SBE data profiles (marine probes)
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker
import os
import glob
import warnings
from collections import defaultdict

# warnings format for warnings messages to be visible
warnings.simplefilter("always", UserWarning)

# %%
# formatting the warning messages


def custom_warning_format(message, category, filename, lineno, line=None):
    return f"\n⚠️  WARNING: {message}\n\n"


warnings.formatwarning = custom_warning_format

# %% parse_somlit_file


def parse_somlit_file(filepath):
    """
    Function is a parser to read a CSV Somlit type file generated by Somlit RBR toolbox
    Not used because missing channels in the final somlit file compared with what
    we want to compare in the SBE data (more channels)

    Parameters
    ----------
    filepath : str
        path to the Somlit csv file

    Raises
    ------
    ValueError
        regarding the format of the first line of the somlit csv

    Returns
    -------
    df : dataframe
        data of the somlit csv sorted in a dataframe

    """
    """
    Parses a SOMLIT-like CSV file with header and metadata.

    Args:
        filepath (str): Path to the input file.

    Returns:
        pd.DataFrame: Cleaned data as DataFrame.
    """

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Find the line that starts with 'ID_SITE' – it's the header
    for i, line in enumerate(lines):
        if line.strip().startswith("ID_SITE"):
            header_idx = i
            break
    else:
        raise ValueError("No header line starting with 'ID_SITE' found.")

    # Now use pandas to read from that line onward
    df = pd.read_csv(
        filepath,
        sep=";",
        skiprows=header_idx,  # skip line with variable too
        encoding="utf-8"
    )

    # Drop completely empty rows (e.g. lines of just semicolons)
    df.dropna(how="all", inplace=True)

    # Remove first row having the units
    df = df.iloc[1:].reset_index(drop=True)

    # Combine date + time into datetime
    df["DATETIME"] = pd.to_datetime(df["DATE"] + " " + df["HEURE"])
    # Convert to datetime64 format
    df['DATETIME'] = pd.to_datetime(df['DATETIME'])

    # Optional: reorder or drop columns
    df = df[["DATETIME", "ID_SITE", "TEMPERATURE",
             "FLUORESCENCE", "PAR", "SALINITE", "PROFONDEUR"]]

    # assign DATETIME colmun as index
    df.set_index('DATETIME', inplace=True)

    return df


# %% read_somlit_csv

def read_somlit_csv(filepath, site_id_filter=None):
    '''
    Generic reader for a SOMLIT-format CSV, whatever produced it: our own
    RBR pipeline (RSKsomlit_proc.toSomlitDB) or a partner lab's SBE profile
    already converted to the SOMLIT layout. Both share the same shape: a
    few comment lines (any prefix, "//" or "#"), a header row starting with
    "ID_SITE", then ";"-separated data rows.

    Unlike parse_somlit_file() above (which assumes exactly one "units" row
    right after the header, true for our RBR output but NOT for a plain SBE
    file where data starts immediately after the header, and would silently
    delete the first real data row), this reader discards non-data rows
    generically: any row whose ID_SITE doesn't parse as a number (units row,
    blank ";;;;;;;", ...) is dropped, regardless of how many such rows exist
    or where they sit.

    It also auto-detects the DATE format per file: our RBR output writes
    ISO "YYYY-MM-DD", while the example SBE file uses "DD-MM-YYYY". Note
    this can NOT be done with pandas' generic dayfirst=True, which silently
    mis-parses an unambiguous ISO date like "2026-05-06" as if day/month
    were swapped whenever both are <=12.

    Parameters
    ----------
    filepath : str
        path to the Somlit-format csv file (RBR or SBE)
    site_id_filter : int, optional
        if given, keep only rows whose ID_SITE matches this value

    Returns
    -------
    df : dataframe
        indexed by DATETIME, with a "DATE" column (python date objects,
        one calendar date per profile) usable for matching RBR vs SBE files
    '''
    lines = _read_text_lines_robust(filepath)

    header_idx = None
    for idx, line in enumerate(lines):
        if line.split(";")[0].strip() == "ID_SITE":
            header_idx = idx
            break
    if header_idx is None:
        raise ValueError(
            f"Ligne d'en-tête 'ID_SITE;...' introuvable dans {filepath}")

    column_names = lines[header_idx].strip().split(";")

    df = pd.read_csv(
        filepath,
        sep=";",
        skiprows=header_idx + 1,
        header=None,
        names=column_names,
        engine="python",
        encoding="cp1252",
    )

    # Drop any non-data row (units row, blank separator row...): a genuine
    # data row always has a numeric ID_SITE.
    df["ID_SITE"] = pd.to_numeric(df["ID_SITE"], errors="coerce")
    df = df.dropna(subset=["ID_SITE"]).reset_index(drop=True)

    if df.empty:
        return df

    # Make sure every value column is numeric (they can come back as object
    # dtype since the raw read mixed in non-numeric junk rows above)
    for col in df.columns:
        if col not in ("DATE", "HEURE"):
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Detect DATE format from the first row: 4-digit first token -> ISO
    # (our RBR output), otherwise DD-MM-YYYY (SBE-style)
    first_date = str(df["DATE"].iloc[0])
    if len(first_date.split("-")[0]) == 4:
        date_format = "%Y-%m-%d"
    else:
        date_format = "%d-%m-%Y"

    df["DATETIME"] = pd.to_datetime(
        df["DATE"] + " " + df["HEURE"],
        format=f"{date_format} %H:%M:%S",
    )
    df["DATE"] = pd.to_datetime(df["DATE"], format=date_format).dt.date

    df = df.set_index("DATETIME").sort_index()

    if site_id_filter is not None:
        df = df[df["ID_SITE"] == site_id_filter]

    return df


def _read_text_lines_robust(file_path):
    '''
    Read all lines of a text file, tolerating the fact that RBR's own CSV
    export (RSK.RSK2CSV) writes files in Windows-1252, not UTF-8. Unit
    symbols in the header/comment lines such as "kg/m³", "µmol/L", "°C" are
    single bytes (e.g. 0xB3 for "³") that are invalid on their own in UTF-8,
    which raises:
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 ...
    when the file is opened with Python's default/UTF-8 text encoding.

    Tries utf-8 first, falls back to cp1252 (RBR's actual encoding), and
    finally latin-1 as a last resort (never raises, decodes every byte).
    '''
    for encoding in ("utf-8", "cp1252"):
        try:
            with open(file_path, "r", encoding=encoding) as f:
                return f.readlines()
        except UnicodeDecodeError:
            continue
    with open(file_path, "r", encoding="latin-1") as f:
        return f.readlines()


# %% read_RBR_csv

def read_RBR_csv(file_path):
    '''
    Function, parser to read a csv file generated by procRSK function and store
    it in a dataframe

    Parameters
    ----------
    file_path : str
        path to the processed csv with RBR data either down or upcast

    Returns
    -------
    df : dataframe
        Dataframe withe the data properly stored to be used later  
    '''

    # NB: robust reader because RBR's RSK2CSV export is written in cp1252,
    # not UTF-8 (see _read_text_lines_robust docstring above).
    lines = _read_text_lines_robust(file_path)

    # Step 2: Find the last line starting with '//'
    header_line_idx = None
    for idx, line in enumerate(lines):
        if line.startswith("//"):
            header_line_idx = idx

    # Step 3: Read the file into DataFrame, skipping earlier lines
    # Beware of sep ',   ' 4 spaces after comma
    df = pd.read_csv(
        file_path,
        sep=',    ',
        skiprows=header_line_idx + 1,     # Skip all lines before actual data
        header=None,                      # No header in data part
        engine="python",
        encoding="cp1252",
    )

    # Step 4: Set the header from the last '//' line
    column_names = lines[header_line_idx].lstrip("//").strip().split(",    ")
    df.columns = column_names

    # remove line with nan
    df = df.dropna()

    # Convert the first column to datetime using your format
    # NB: assign via the column label (not .iloc), see RSKsomlit_proc.toSomlitDB
    # for why (recent pandas StringDtype inference + strict .iloc setitem).
    first_col = df.columns[0]
    df[first_col] = pd.to_datetime(df[first_col], format='%Y-%m-%dT%H:%M:%S.%f')

    # Set the first column as the index, and avoid warning caused
    # by aving diffrent object types in the index: str, numerical, etc...
    df[df.columns[0]] = df[df.columns[0]].infer_objects()
    df.set_index(df.columns[0], inplace=True)

    return df

# %% parse_custom_sbe


def parse_custom_sbe(filepath):
    '''
    Function, parser specially adapted for sbe file for sept 2025
    sbe file generation is done by Emily manually and column names, order varies
    which programd don't like. parser must be adapted or adaptative

    Parameters
    ----------
    filepath : str
        Path to the sbe csv file to read

    Returns
    -------
    df : dataframe
        dataframe to be used in later processing with all seb data inside

    '''
    # Read file, skip second line (units), first line is header
    df = pd.read_csv(
        filepath,
        sep=';',
        skiprows=[1],  # skip the units row
        decimal=',',    # interpret comma as decimal separator
        dayfirst=True,  # because date format is DD/MM/YYYY
    )

    # Combine date and time into a datetime column
    df['DATETIME'] = pd.to_datetime(
        df['DD MMM YYYY'] + ' ' + df['HH:MM:SS'], dayfirst=True)

    # Set DATETIME as index
    df.set_index('DATETIME', inplace=True)

    # Optional: drop original date/time columns if you want
    df.drop(columns=['DD MMM YYYY', 'HH:MM:SS'], inplace=True)

    return df

# %% rename_sbe_columns


def rename_sbe_columns(df_sbe, df_rbr):
    '''
    Function to rename the columns of sbe df with the ones from rbr df using 
    position id
    + apply a factor to convert DO from ml/L (sbe) to micromol/L (RBR)

    Parameters
    ----------
    df_sbe : dataframe
       sbe dataframe comes from parser function above
    df_rbr : dataframe
        rbr dataframe comes from the parser function above


    Returns
    -------
    df_sbe : dataframe
       columns have been renamed to be the same as rbr and ease the comparison

    '''
    # expected SBE columns (before renaming), list the excpected column names in SBE csv file
    expected_columns = {
        'temp',
        'FLUO',
        'Par',
        'conductivité',
        'Oxygène',
        'turbidité',
        'Sal00',
        'profondeur',
        'densité',
    }
    # find unexpected columns
    unexpected_cols = set(df_sbe.columns) - expected_columns
    if unexpected_cols:
        warnings.warn(
            f"Unexpected column(s) found in SBE dataframe: {
                sorted(unexpected_cols)}"
        )
    # unit convsersion for DO
    # apply a factor to DO values from SBE to convert units
    # from ml/L to micromol/L
    df_sbe['Oxygène'] = df_sbe['Oxygène'] * 44.66

    # rename columns as per the RBR names
    rename_dict = {
        'temp': df_rbr.columns[1],
        'FLUO': df_rbr.columns[6],
        'Par': df_rbr.columns[4],
        'conductivité': df_rbr.columns[0],
        'Oxygène': df_rbr.columns[3],
        'turbidité': df_rbr.columns[8],
        'Sal00': df_rbr.columns[10],
        'profondeur': df_rbr.columns[9],
        'densité': df_rbr.columns[11],
    }

    df_sbe = df_sbe.rename(columns=rename_dict)

    # dodgy option, we had a miror colum with DO values but named differently to
    # allow a comparison with DO_compensated values from RBR
    df_sbe['dissolved_o2_compensated(µmol/L)'] = df_sbe['dissolved_o2_concentration(µmol/L)']

    return df_sbe

# %% plot_and_save_comparisons_all_columns


def plot_and_save_comparisons_all_columns(df_sbe, df_rbr, depth_col='depth(m)', save_folder='figures'):
    """
    Works for upcast and downcast, surpassed by the next function that plots
    everything on the same graph
    Compare all common numeric columns from SBE and RBR:
    - Plot each parameter vs depth on a fig.
    - Plot the difference (SBE - RBR) vs depth (only at common depths) on a fig.
    - Save plots as PNG files

    Args:
        df_sbe (pd.DataFrame): SBE dataset
        df_rbr (pd.DataFrame): RBR dataset
        depth_col (str): Name of the depth column
        save_folder (str): Output directory
    """
    os.makedirs(save_folder, exist_ok=True)

    # Ensure depth columns are numeric and rounded to avoid tiny float mismatches
    df_sbe[depth_col] = pd.to_numeric(
        df_sbe[depth_col], errors='coerce').round(4)
    df_rbr[depth_col] = pd.to_numeric(
        df_rbr[depth_col], errors='coerce').round(4)

    # Find common depths
    common_depths = np.intersect1d(
        df_sbe[depth_col].dropna().unique(), df_rbr[depth_col].dropna().unique())

    if len(common_depths) == 0:
        print("❌ No common depth values found between datasets.")
        return

    # Filter both DataFrames to common depths
    df_sbe_common = df_sbe[df_sbe[depth_col].isin(common_depths)].copy()
    df_rbr_common = df_rbr[df_rbr[depth_col].isin(common_depths)].copy()

    # Sort by depth for plotting
    df_sbe_common = df_sbe_common.sort_values(depth_col)
    df_rbr_common = df_rbr_common.sort_values(depth_col)

    # Get common numeric columns (excluding depth)
    common_cols = [
        col for col in df_rbr.columns
        if col in df_sbe.columns
        and col != depth_col
        and pd.api.types.is_numeric_dtype(df_rbr[col])
    ]

    if not common_cols:
        print("❌ No common numeric columns to compare.")
        return

    for param in common_cols:
        print(f"📈 Processing '{param}'...")

        # Merge on depth to align values exactly
        merged = pd.merge(
            df_sbe_common[[depth_col, param]],
            df_rbr_common[[depth_col, param]],
            on=depth_col,
            suffixes=('_sbe', '_rbr')
        )

        if merged.empty:
            print(f"⚠️ No matching depth values with data for '{
                  param}'. Skipping.")
            continue

        # Plot parameter vs depth
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.plot(merged[f"{param}_sbe"], merged[depth_col],
                label='SBE', marker='o')
        ax.plot(merged[f"{param}_rbr"], merged[depth_col],
                label='RBR', marker='x')
        ax.invert_yaxis()
        ax.set_xlabel(f"{param} (units)")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Profile: SBE vs RBR")
        ax.legend()
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        safe_param = ''.join(c if c.isalnum() or c in [
                             '_', '-'] else '_' for c in param)
        fig_path_raw = os.path.join(save_folder, f"{safe_param}_profile.png")
        fig.savefig(fig_path_raw, dpi=150)
        plt.close(fig)

        # Compute difference on common depths
        diff = merged[f"{param}_rbr"] - merged[f"{param}_sbe"]

        # Plot difference
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.plot(diff, merged[depth_col],
                label='RBR - SBE', color='red', marker='.')
        ax.invert_yaxis()
        ax.set_xlabel(f"{param} Difference")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Difference (RBR - SBE)")
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        fig_path_diff = os.path.join(
            save_folder, f"{safe_param}_difference.png")
        fig.savefig(fig_path_diff, dpi=150)
        plt.close(fig)

        print(f"✅ Saved: {fig_path_raw} and {fig_path_diff}")

# %% plot_comparison_up_down
# produces figures with up and down cast and both sbe and rbr data on the same graph, great


def plot_comparisons_up_down(
        df_sbe_down, df_rbr_down,
        df_sbe_up, df_rbr_up,
        depth_col='depth(m)',
        save_folder='figures'):
    '''
    Function to produce figures with up and down cast both on the same graph 
    for both SBE (seabird) and RBR data

    Parameters
    ----------
    df_sbe_down : dataframe
        sbe data downcast
    df_rbr_down : dataframe
        rbr data downcast
    df_sbe_up : dataframe
        sbe data upcast
    df_rbr_up : dataframe
        rbr data upcast
    depth_col : str
        column name with the depth data. The default is 'depth(m)'.
    save_folder : str, optional
        output folder with the figures. The default is 'figures'.

    Returns
    -------
    None

    '''
    os.makedirs(save_folder, exist_ok=True)

    def preprocess(df):
        df = df.copy()
        df[depth_col] = pd.to_numeric(df[depth_col], errors='coerce').round(4)
        return df.dropna(subset=[depth_col])

    df_sbe_down = preprocess(df_sbe_down)
    df_rbr_down = preprocess(df_rbr_down)
    df_sbe_up = preprocess(df_sbe_up)
    df_rbr_up = preprocess(df_rbr_up)

    # Get common numeric columns
    common_cols = [
        col for col in df_rbr_down.columns
        if col in df_sbe_down.columns
        and col != depth_col
        and pd.api.types.is_numeric_dtype(df_rbr_down[col])
    ]

    if not common_cols:
        print("❌ No common numeric columns to compare.")
        return

    for param in common_cols:
        print(f"📈 Processing '{param}'...")

        # Prepare merged data for both casts
        def merge_on_depth(df1, df2):
            common_depths = np.intersect1d(
                df1[depth_col].unique(), df2[depth_col].unique())
            df1_common = df1[df1[depth_col].isin(common_depths)]
            df2_common = df2[df2[depth_col].isin(common_depths)]
            return pd.merge(
                df1_common[[depth_col, param]],
                df2_common[[depth_col, param]],
                on=depth_col,
                suffixes=('_sbe', '_rbr')
            ).sort_values(depth_col)

        merged_down = merge_on_depth(df_sbe_down, df_rbr_down)
        merged_up = merge_on_depth(df_sbe_up, df_rbr_up)

        # Profile Plot
        fig, ax = plt.subplots(figsize=(8, 6))
        if not merged_down.empty:
            ax.plot(merged_down[f"{param}_sbe"],
                    merged_down[depth_col], 'o-', label='SBE Downcast')
            ax.plot(merged_down[f"{param}_rbr"],
                    merged_down[depth_col], 'x-', label='RBR Downcast')
        if not merged_up.empty:
            ax.plot(merged_up[f"{param}_sbe"], merged_up[depth_col],
                    'o--', label='SBE Upcast', alpha=0.6)
            ax.plot(merged_up[f"{param}_rbr"], merged_up[depth_col],
                    'x--', label='RBR Upcast', alpha=0.6)

        ax.invert_yaxis()
        ax.set_xlabel(f"{param} (units)")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Profile: Upcast & Downcast (SBE vs RBR)")
        ax.legend()
        ax.grid(True)
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        safe_param = ''.join(c if c.isalnum() or c in [
                             '_', '-'] else '_' for c in param)
        fig_path_profile = os.path.join(
            save_folder, f"{safe_param}_profile.png")
        fig.savefig(fig_path_profile, dpi=150)
        plt.close(fig)

        # Difference Plot (RBR - SBE)
        fig, ax = plt.subplots(figsize=(6, 6))
        if not merged_down.empty:
            diff_down = merged_down[f"{param}_rbr"] - \
                merged_down[f"{param}_sbe"]
            ax.plot(diff_down, merged_down[depth_col], 'r-',
                    label='Downcast (RBR - SBE)', marker='.')
        if not merged_up.empty:
            diff_up = merged_up[f"{param}_rbr"] - merged_up[f"{param}_sbe"]
            ax.plot(diff_up, merged_up[depth_col], 'b--',
                    label='Upcast (RBR - SBE)', marker='.')

        ax.invert_yaxis()
        ax.set_xlabel(f"{param} Difference")
        ax.set_ylabel("Depth (m)")
        ax.set_title(f"{param} Difference (RBR - SBE)")
        ax.grid(True)
        ax.legend()
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.3f'))
        plt.tight_layout()

        fig_path_diff = os.path.join(
            save_folder, f"{safe_param}_difference.png")
        fig.savefig(fig_path_diff, dpi=150)
        plt.close(fig)

        print(f"✅ Saved: {fig_path_profile} and {fig_path_diff}")


# %% find_rbr_somlit_files

def find_rbr_somlit_files(rbr_root):
    '''
    Recursively find every RBR-produced Somlit CSV under rbr_root (typically
    proc_data/outputs/), i.e. every file matching "*_4somlit_*.csv" as
    written by RSKsomlit_proc.toSomlitDB() (one per downcast/upcast/profile).

    Parameters
    ----------
    rbr_root : str
        root folder to search recursively (e.g. proc_data/outputs)

    Returns
    -------
    list of str
        sorted list of matching file paths
    '''
    return sorted(glob.glob(os.path.join(rbr_root, "**", "*_4somlit_*.csv"),
                             recursive=True))


# %% find_sbe_files

def find_sbe_files(sbe_root):
    '''
    Find every SBE csv file directly inside sbe_root (e.g. SBE_completed/),
    already in the Somlit-like layout provided by the partner lab.

    Parameters
    ----------
    sbe_root : str
        folder containing the SBE csv files (not searched recursively)

    Returns
    -------
    list of str
        sorted list of matching file paths
    '''
    return sorted(glob.glob(os.path.join(sbe_root, "*.csv")))


# %% match_rbr_sbe_by_date

def match_rbr_sbe_by_date(rbr_root, sbe_root):
    '''
    Scan rbr_root for RBR Somlit CSVs and sbe_root for SBE Somlit CSVs, read
    each one, and group them by calendar date (the DATE of their first data
    row). Returns one entry per date found in BOTH sources, ready to be
    compared pairwise.

    A file that fails to parse (unexpected format, empty after cleaning...)
    is skipped with a [WARNING], not fatal to the rest of the run.

    Parameters
    ----------
    rbr_root : str
        root folder to search recursively for RBR Somlit CSVs
    sbe_root : str
        folder to search (non-recursively) for SBE Somlit CSVs

    Returns
    -------
    list of dict
        one dict per matching date: {"date": date,
                                      "rbr": [(filepath, df), ...],
                                      "sbe": [(filepath, df), ...]}
        sorted by date
    '''
    rbr_by_date = defaultdict(list)
    sbe_by_date = defaultdict(list)

    for f in find_rbr_somlit_files(rbr_root):
        try:
            df = read_somlit_csv(f)
            if df.empty:
                print(f"[WARNING] {f} ne contient aucune ligne de donnée exploitable, ignoré.")
                continue
            rbr_by_date[df["DATE"].iloc[0]].append((f, df))
        except Exception as e:
            print(f"[WARNING] Impossible de lire {f} comme CSV Somlit RBR: {e}")

    for f in find_sbe_files(sbe_root):
        try:
            df = read_somlit_csv(f)
            if df.empty:
                print(f"[WARNING] {f} ne contient aucune ligne de donnée exploitable, ignoré.")
                continue
            sbe_by_date[df["DATE"].iloc[0]].append((f, df))
        except Exception as e:
            print(f"[WARNING] Impossible de lire {f} comme CSV Somlit SBE: {e}")

    common_dates = sorted(set(rbr_by_date) & set(sbe_by_date))

    if not common_dates:
        print("❌ Aucune date commune trouvée entre les fichiers RBR et SBE.")
    else:
        print(f"📅 {len(common_dates)} date(s) commune(s) trouvée(s): "
              f"{[str(d) for d in common_dates]}")

    return [
        {"date": d, "rbr": rbr_by_date[d], "sbe": sbe_by_date[d]}
        for d in common_dates
    ]


# %% compare_all_matching_dates

def compare_all_matching_dates(rbr_root, sbe_root, save_folder="figures_comparison_SBE_RBR"):
    '''
    Main entry point: automatically find every (RBR Somlit csv, SBE Somlit
    csv) pair that shares the same calendar date, and produce comparison
    plots (profile overlay + difference, per common physical parameter) for
    each pair. If a date has several RBR files (e.g. downcast AND upcast)
    and/or several SBE files, every RBR/SBE combination for that date is
    compared.

    Comparisons are made only on columns common to both files (typically
    TEMPERATURE, FLUORESCENCE, PAR, SALINITE — TURBIDITE when the RBR side
    also has it, which isn't the case for a Maestro without a fluorometer/
    turbidity sensor exported, or a Concerto). ID_SITE is excluded from the
    comparison (it's a station identifier, not a physical measurement).

    A mismatched ID_SITE between a paired RBR/SBE file (same date, different
    station) is reported as a [WARNING] but does not block the comparison -
    review it if it happens, it may mean two different stations happened to
    be sampled the same day.

    Parameters
    ----------
    rbr_root : str
        root folder to search recursively for RBR Somlit CSVs (e.g.
        proc_data/outputs)
    sbe_root : str
        folder containing the SBE Somlit CSVs (e.g. SBE_completed)
    save_folder : str, optional
        root folder where comparison figures are saved, one subfolder per
        date. Default "figures_comparison_SBE_RBR".

    Returns
    -------
    None
    '''
    matches = match_rbr_sbe_by_date(rbr_root, sbe_root)

    for entry in matches:
        date = entry["date"]
        date_str = date.strftime("%Y-%m-%d")

        for rbr_path, df_rbr in entry["rbr"]:
            # "_4somlit_d.csv" -> downcast, "_4somlit_u.csv" -> upcast
            cast = "downcast" if rbr_path.endswith("_d.csv") else \
                   "upcast" if rbr_path.endswith("_u.csv") else "profile"
            rbr_label = os.path.splitext(os.path.basename(rbr_path))[0]

            for sbe_path, df_sbe in entry["sbe"]:
                sbe_label = os.path.splitext(os.path.basename(sbe_path))[0]

                rbr_site = df_rbr["ID_SITE"].iloc[0]
                sbe_site = df_sbe["ID_SITE"].iloc[0]
                if rbr_site != sbe_site:
                    print(f"[WARNING] {date_str}: ID_SITE différent entre "
                          f"RBR ({rbr_label}, site {rbr_site}) et SBE "
                          f"({sbe_label}, site {sbe_site}) — comparaison "
                          f"effectuée quand même, à vérifier.")

                print(f"\n🔎 Comparaison {date_str} [{cast}]: "
                      f"{rbr_label}  vs  {sbe_label}")

                pair_folder = os.path.join(
                    save_folder, date_str, f"{rbr_label}_vs_{sbe_label}"
                )

                # ID_SITE isn't a physical measurement - drop it from the
                # comparison so it isn't plotted as if it were a channel.
                plot_and_save_comparisons_all_columns(
                    df_sbe.drop(columns=["ID_SITE"], errors="ignore"),
                    df_rbr.drop(columns=["ID_SITE"], errors="ignore"),
                    depth_col="PROFONDEUR",
                    save_folder=pair_folder,
                )